<a href="https://colab.research.google.com/github/Sadnya20/Projects/blob/main/top10GDP_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
## Project Title: Top 10 Largest Economies by GDP

## Project Scenario
##An international firm aiming to expand its business globally has recruited me as a junior Data Engineer.
## My task is to create a script that extracts the list of the top 10 largest economies in the world based
##on their Gross Domestic Product (GDP) in Billion USD, as recorded by the International Monetary Fund (IMF).

In [1]:
import numpy as np
import pandas as pd

# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

In [2]:
URL="https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"

In [30]:
from os import replace
import pandas as pd

# URL containing the table
url = "https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"

# Read tables from the URL
tables = pd.read_html(url)
print(tables)
df=tables[3]
df
print(df.head(10))  # Display the first few rows
print(df.columns)  # Display the column names
print("Columns:", df.columns.tolist())
#cleaning the columns names
df.columns = [(col[0].strip(), col[1].strip()) for col in df.columns]
# now  stripping the columns we actually needs
print(df.columns)
print(df.columns[2:5])
#making  df for  needed values
df = df[[df.columns[0]] + list(df.columns[2:4])]
print(df)
 #Rename columns as necessary
df.columns = ["Country", "GDP (Million USD)","Year"]
df.columns[2]
print(df.head(2))
# retaining the top  10 countriess with high gdp
df = df.iloc[1:11, :]
print(df)
## Check the current column names
print(df.columns)
#converting gdp to  float divede by 1000 and then in integer
df['GDP (Million USD)'] = df['GDP (Million USD)'].astype(float)
df['GDP (Million USD)'] = df['GDP (Million USD)'].astype(int)
#converting USD million into billion
df['GDP (Million USD)'] = df['GDP (Million USD)']/1000
df.columns = ["Country", "GDP (Billion USD)","Year"]
print(df)

[      0     1     2
0   Aug   SEP   Oct
1   NaN    02   NaN
2  2022  2023  2024,                                                    0
0  Largest economies in the world by GDP (nominal...,                                                    0  \
0  > $20 trillion $10–20 trillion $5–10 trillion ...

                                                   1  \
0  $750 billion – $1 trillion $500–750 billion $2...

                                                   2
0  $50–100 billion $25–50 billion $5–25 billion <...  ,     Country/Territory UN region IMF[1][13]            World Bank[14]  \
    Country/Territory UN region   Estimate       Year       Estimate
0               World         —  105568776       2023      100562011
1       United States  Americas   26854599       2023       25462700
2               China      Asia   19373586  [n 1]2023       17963171
3               Japan      Asia    4409738       2023        4231141
4             Germany    Europe    4308854       2023        4072192
..                ...       ...        ...        ...            ...
209          Anguilla  Americas          —          —              —
210          Kiribati   Oceania        248       2023            223
211             Nauru   Oceania        151       2023            151
212        Montserrat  Americas          —          —              —
213            Tuvalu   Oceania         65       2023             60

               United Nations[15]
          Year           Estimate       Year
0         2022           96698005       2021
1         2022           23315081       2021
2    [n 3]2022           17734131  [n 1]2021
3         2022            4940878       2021
4         2022            4259935       2021
..         ...                ...        ...
209          —                303       2021
210       2022                227       2021
211       2022                155       2021
212          —                 72       2021
213       2022                 60       2021

[214 rows x 8 columns],          vteLists of countries by financial rankings  \
0                                              Trade
1                                         Investment
2                                              Funds
3                                    Budget and debt
4                                   Income and taxes
5                                         Bank rates
6                                           Currency
7                                              Other
8  Lists of countries by GDP rankings List of int...

       vteLists of countries by financial rankings.1
0  Account balance % of GDP Exports by product me...
1                   FDI received past FDI abroad GFI
2  Forex reserves Forex reserves (ex. gold) Gold ...
3  Government budget PPP % of GDP per capita Cred...
4  Tax rates Inheritance tax Tax revenue Wage ave...
5  Central bank interest rate Commercial bank pri...
6               Exchange rates to US$ Inflation rate
7  Financial Development Index Average annual lab...
8  Lists of countries by GDP rankings List of int...  ,                vteLists of countries by GDP rankings  \
0                                            Nominal
1                      Purchasing power parity (PPP)
2                                        Growth rate
3                        Gross national income (GNI)
4                                Countries by region
5                              Subnational divisions
6  Lists of countries by financial rankings List ...

             vteLists of countries by GDP rankings.1
0  Per capita Past and projected per capita Secto...
1  Per capita Past per capita Past and projected ...
2  African countries Asian states European Union ...
3                  PPP per capita Nominal per capita
4  Africa PPP nominal Commonwealth of Nations PPP...
5  Albania Argentina Australia Austria Baltic Sta...
6  Lists of countries by financial rankings List ...  ,               vteEconomic classification of countries  \
0   Developed country Developing country Least dev...
1                                   Three-World Model
2                        Gross domestic product (GDP)
3                                             Nominal
4                       Purchasing power parity (PPP)
5                         Gross national income (GNI)
6                                               Wages
7                                              Wealth
8                             Other national accounts
9                                   Human development
10                                     Digital divide
11       Net international investment position (NIIP)
12                    Economics portal • World portal

            vteEconomic classification of countries.1
0   Developed country Developing country Least dev...
1   First World Second World Third World Fourth World
2   Nominal By country past and projected per capi...
3   By country past and projected per capita per c...
4   By country future estimates per capita per cap...
5   (Nominal, Atlas method) per capita (PPP) per c...
6   Average wage Europe Employee compensation (per...
7   Wealth per adult Europe Financial assets per c...
8   Gross National Happiness Net material product ...
9   Human Development Index by country inequality-...
10  ICT Development Index Number of broadband Inte...
11        Per capita (creditors) Per capita (debtors)
12                    Economics portal • World portal  ,                                0  \
0                        Nominal
1  Purchasing power parity (PPP)

                                                   1
0  By country past and projected per capita per c...
1  By country future estimates per capita per cap...  ]
  Country/Territory UN region IMF[1][13]            World Bank[14]             \
  Country/Territory UN region   Estimate       Year       Estimate       Year
0             World         —  105568776       2023      100562011       2022
1     United States  Americas   26854599       2023       25462700       2022
2             China      Asia   19373586  [n 1]2023       17963171  [n 3]2022
3             Japan      Asia    4409738       2023        4231141       2022
4           Germany    Europe    4308854       2023        4072192       2022
5             India      Asia    3736882       2023        3385090       2022
6    United Kingdom    Europe    3158938       2023        3070668       2022
7            France    Europe    2923489       2023        2782905       2022
8             Italy    Europe    2169745       2023        2010432       2022
9            Canada  Americas    2089672       2023        2139840       2022

  United Nations[15]
            Estimate       Year
0           96698005       2021
1           23315081       2021
2           17734131  [n 1]2021
3            4940878       2021
4            4259935       2021
5            3201471       2021
6            3131378       2021
7            2957880       2021
8            2107703       2021
9            1988336       2021
MultiIndex([( 'Country/Territory', 'Country/Territory'),
            (         'UN region',         'UN region'),
            (        'IMF[1][13]',          'Estimate'),
            (        'IMF[1][13]',              'Year'),
            (    'World Bank[14]',          'Estimate'),
            (    'World Bank[14]',              'Year'),
            ('United Nations[15]',          'Estimate'),
            ('United Nations[15]',              'Year')],
           )
Columns: [('Country/Territory', 'Country/Territory'), ('UN region', 'UN region'), ('IMF[1][13]', 'Estimate'), ('IMF[1][13]', 'Year'), ('World Bank[14]', 'Estimate'), ('World Bank[14]', 'Year'), ('United Nations[15]', 'Estimate'), ('United Nations[15]', 'Year')]
Index([('Country/Territory', 'Country/Territory'),
                       ('UN region', 'UN region'),
                       ('IMF[1][13]', 'Estimate'),
                           ('IMF[1][13]', 'Year'),
                   ('World Bank[14]', 'Estimate'),
                       ('World Bank[14]', 'Year'),
               ('United Nations[15]', 'Estimate'),
                   ('United Nations[15]', 'Year')],
      dtype='object')
Index([    ('IMF[1][13]', 'Estimate'),         ('IMF[1][13]', 'Year'),
       ('World Bank[14]', 'Estimate')],
      dtype='object')
    (Country/Territory, Country/Territory) (IMF[1][13], Estimate)  \
0                                    World              105568776
1                            United States               26854599
2                                    China               19373586
3                                    Japan                4409738
4                                  Germany                4308854
..                                     ...                    ...
209                               Anguilla                      —
210                               Kiribati                    248
211                                  Nauru                    151
212                             Montserrat                      —
213                                 Tuvalu                     65

    (IMF[1][13], Year)
0                 2023
1                 2023
2            [n 1]2023
3                 2023
4                 2023
..                 ...
209                  —
210               2023
211               2023
212                  —
213               2023

[214 rows x 3 columns]
         Country GDP (Million USD)  Year
0          World         105568776  2023
1  United States          26854599  2023
           Country GDP (Million USD)       Year
1    United States          26854599       2023
2            China          19373586  [n 1]2023
3            Japan           4409738       2023
4          Germany           4308854       2023
5            India           3736882       2023
6   United Kingdom           3158938       2023
7           France           2923489       2023
8            Italy           2169745       2023
9           Canada           2089672       2023
10          Brazil           2081235       2023
Index(['Country', 'GDP (Million USD)', 'Year'], dtype='object')
           Country  GDP (Billion USD)       Year
1    United States          26854.599       2023
2            China          19373.586  [n 1]2023
3            Japan           4409.738       2023
4          Germany           4308.854       2023
5            India           3736.882       2023
6   United Kingdom           3158.938       2023
7           France           2923.489       2023
8            Italy           2169.745       2023
9           Canada           2089.672       2023
10          Brazil           2081.235       2023

In [31]:
print ('Final Dataframe:')
print(df)

Final Dataframe:
           Country  GDP (Billion USD)       Year
1    United States          26854.599       2023
2            China          19373.586  [n 1]2023
3            Japan           4409.738       2023
4          Germany           4308.854       2023
5            India           3736.882       2023
6   United Kingdom           3158.938       2023
7           France           2923.489       2023
8            Italy           2169.745       2023
9           Canada           2089.672       2023
10          Brazil           2081.235       2023

In [40]:
import pandas as pd

# Example DataFrame (replace with your actual DataFrame)
# df = pd.DataFrame({'Country': ['A', 'B'], 'GDP (Million USD)': [1000, 2000]})

# Define the path for saving the CSV file
csv_file_path = r"C:\Users\Darshika\Desktop\Snake\docking\Countrywise_highest_economy.csv"

# Saving the DataFrame to CSV
df.to_csv(csv_file_path, index=False)
print("Data saved to Countrywise_highest_economy.csv")

Data saved to Countrywise_highest_economy.csv

In [42]:
# Reading the DataFrame back from CSV
try:
    dfnew = pd.read_csv(r'C:\Users\Darshika\Desktop\Snake\docking\Countrywise_highest_economy.csv')
    print("Data read from Countrywise_highest_economy.csv:")
    print(dfnew)
except FileNotFoundError as e:
    print(f"Error: {e}")

Data read from Countrywise_highest_economy.csv:
          Country  GDP (Billion USD)       Year
0   United States          26854.599       2023
1           China          19373.586  [n 1]2023
2           Japan           4409.738       2023
3         Germany           4308.854       2023
4           India           3736.882       2023
5  United Kingdom           3158.938       2023
6          France           2923.489       2023
7           Italy           2169.745       2023
8          Canada           2089.672       2023
9          Brazil           2081.235       2023